"""Tests for memory models (SQLModel)."""

import pytest
from datetime import datetime
import uuid
from src.core.memory.models import Project, ChatSession, ChatMessage


class TestProjectModel:
    """Test cases for Project model."""

    def test_project_creation(self, sample_project_data):
        """Test basic Project model creation."""
        project = Project(**sample_project_data)
        assert project.id == sample_project_data["id"]
        assert project.name == "Test Project"
        assert project.description == "A test project"
        assert project.color == "#7c3aed"
        assert project.icon == "📁"
        assert isinstance(project.created_at, datetime)

    def test_project_default_values(self):
        """Test Project model default values."""
        project = Project(name="Test Project")
        assert project.color == "#7c3aed"  # Default purple
        assert project.icon == "📁"  # Default folder emoji
        assert project.description is None
        assert project.context_summary is None
        assert isinstance(project.id, str)  # UUID generated

    def test_project_id_is_uuid(self):
        """Test that project ID is a valid UUID string."""
        project = Project(name="Test")
        # Should be a valid UUID format
        uuid.UUID(project.id)

    def test_project_relationship(self, sample_project_data):
        """Test Project relationship to ChatSession."""
        project = Project(**sample_project_data)
        # Initially sessions should be empty list (relationship)
        assert project.sessions == []


class TestChatSessionModel:
    """Test cases for ChatSession model."""

    def test_session_creation(self, sample_session_data):
        """Test basic ChatSession model creation."""
        session = ChatSession(**sample_session_data)
        assert session.id == sample_session_data["id"]
        assert session.title == "Test Chat"
        assert session.project_id is None
        assert isinstance(session.created_at, datetime)

    def test_session_default_values(self):
        """Test ChatSession model default values."""
        session = ChatSession()
        assert session.id is None  # Optional, will be generated by DB
        assert session.project_id is None
        assert session.title is None
        assert isinstance(session.created_at, datetime)

    def test_session_with_project(self, sample_project_data):
        """Test ChatSession with associated project."""
        project_id = str(uuid.uuid4())
        session = ChatSession(
            title="Project Chat",
            project_id=project_id
        )
        assert session.project_id == project_id

    def test_session_relationships(self, sample_session_data):
        """Test ChatSession relationships."""
        session = ChatSession(**sample_session_data)
        assert session.project is None  # Not loaded
        assert session.messages == []  # Empty relationship


class TestChatMessageModel:
    """Test cases for ChatMessage model."""

    def test_message_creation(self, sample_message_data):
        """Test basic ChatMessage model creation."""
        message = ChatMessage(**sample_message_data)
        assert message.id == 1
        assert message.session_id == sample_message_data["session_id"]
        assert message.role == "user"
        assert message.content == "Hello, this is a test message"
        assert isinstance(message.created_at, datetime)

    def test_message_roles(self):
        """Test different message roles."""
        session_id = str(uuid.uuid4())

        user_msg = ChatMessage(session_id=session_id, role="user", content="Hello")
        assert user_msg.role == "user"

        assistant_msg = ChatMessage(session_id=session_id, role="assistant", content="Hi!")
        assert assistant_msg.role == "assistant"

        system_msg = ChatMessage(session_id=session_id, role="system", content="System prompt")
        assert system_msg.role == "system"

    def test_message_default_id(self):
        """Test that message ID defaults to None (auto-increment)."""
        session_id = str(uuid.uuid4())
        message = ChatMessage(session_id=session_id, role="user", content="Test")
        assert message.id is None  # Will be set by database

    def test_message_relationship(self, sample_message_data):
        """Test ChatMessage relationship to ChatSession."""
        message = ChatMessage(**sample_message_data)
        assert message.session is None  # Not loaded


class TestModelValidation:
    """Test model validation and constraints."""

    def test_project_name_required(self):
        """Test that project name is required."""
        with pytest.raises(Exception):
            Project.model_validate({})  # name is required

    def test_message_session_id_required(self):
        """Test that message session_id is required."""
        with pytest.raises(Exception):
            ChatMessage.model_validate({"role": "user", "content": "Test"})  # session_id required

    def test_message_role_required(self):
        """Test that message role is required."""
        session_id = str(uuid.uuid4())
        with pytest.raises(Exception):
            ChatMessage.model_validate({"session_id": session_id, "content": "Test"})  # role required

    def test_message_content_required(self):
        """Test that message content is required."""
        session_id = str(uuid.uuid4())
        with pytest.raises(Exception):
            ChatMessage.model_validate({"session_id": session_id, "role": "user"})  # content required
